### ISSUE TITLE
VALIDATION_TYPE_REQUIRED - SELECT

### ISSUE THREAD

**Issue by Gochip** [dsbarrionuevo/ValidationJS#10]
En el VALIDATION_TYPE_REQUIRED aplicado a un SELECT debería poder pasarle un parámetro indicando qué valor es el que indica que está "vacío".

**Comment by dsbarrionuevo** [comment]
Esto lo resuelvo agregando dos nuevos parámetros a la validación tipo VALIDATION_TYPE_REQUIRED al campo de tipo SELECT:
- invalidRequiredValue: permite comparar la situación de "nada seleccionado" en los select usando un string como option.
- checkRequiredMethod: es independiente del anterior, es una función cuyo parámetro es el valor del elemento seleccionado en la lista y devuelve true si es un valor considareado o false en caso de que se quiera marcar que no seleccionó nada.
