### ISSUE TITLE
Agregar función a ejecutar antes de las validaciones

### ISSUE THREAD

**Issue by Gochip** [dsbarrionuevo/ValidationJS#6]
Estaría bueno que haya un método que permita ejecutar código antes que las validaciones se empiecen a ejecutar, por ejemplo, sería útil para hacer algún cálculo o mostrar algún mensaje...

**Comment by dsbarrionuevo** [comment]
Creo funciones before y after. Before tiene como parámetros: event, validationType (tipo de validacion: submit, blur, change), y los ids de los campos del validador (deberían ser los objetos jquery quizás). After tiene sólo el event.
